version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - "5379:6379"
  heus-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5101:80"
