version: '3.4'

services:
  redis:
    image: redis:alpine

  heus-web:
    image: ${DOCKER_REGISTRY-heus}/heus.web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Heus.Web/Dockerfile
    depends_on:
      - redis
